### ISSUE TITLE
Option to not exit on error

### ISSUE THREAD

**Issue by rouke-broersma** [buildarr/buildarr#143]
When I have a configuration error or if one of my hosts is offline I would want buildarr to not exit on error so I can simply fix the configuration or fix my other hosts.

**Comment by Callum027** [comment]
Thanks for the suggestion. I think when running in daemon mode this is the correct behaviour for Buildarr in general, so I'll implement it as such in the next minor release.

**Comment by Callum027** [comment]
https://github.com/buildarr/buildarr/pull/151

**Comment by Callum027** [comment]
Thanks for waiting. the fix for this issue has been released as:

* Python package: `buildarr==0.7.0`
* Docker container: `callum027/buildarr:0.7.0`

Please give the new version a try to check that it resolves your issue.
